id: PB123F42A
initial_creation_type: input
source_metadata:
  Title: Śūnyatāsaptatiḥ
  Editor: Dorje, Acarya Sempa
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1985'
  Śūnyatāsaptatiḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:40:55.910684'
last_modified_at: '2022-03-08T16:40:55.910694'
